### ISSUE TITLE
Not implemented type annotation EmptyStatement

### ISSUE THREAD

**Issue by EliBates** [Rich-Harris/esrap#17]
Hello, I just noticed this in my CI/CD pipeline on cloudflare pages running sveltekit.
[vite-plugin-svelte] [plugin vite-plugin-svelte] Not implemented type annotation EmptyStatement

I identified this peer dep moving from v1.2.3 -> v1.3.2 as the cause, but appears since v1.3.0.

<pre class="c_c c_bw c_pq c_gm c_gd c_ge c_de c_acq c_ags c_agt c_agu c_fc c_fd c_age c_by c_agv">
01:50:50.970 | ✓ 1 modules transformed.
-- | --
01:50:50.971 | x Build failed in 649ms
01:50:50.971 | error during build:
01:50:50.971 | [vite-plugin-svelte] [plugin vite-plugin-svelte] Not implemented type annotation EmptyStatement
01:50:50.971 | file: /opt/buildhome/repo/src/routes/+layout.svelte
01:50:50.972 | Error: [plugin vite-plugin-svelte] Not implemented type annotation EmptyStatement
01:50:50.972 | at handle_type_annotation (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:560:10)
01:50:50.972 | at ObjectPattern (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:1225:28)
01:50:50.972 | at handle (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:62:2)
01:50:50.973 | at VariableDeclarator (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:1531:3)
01:50:50.973 | at handle (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:62:2)
01:50:50.973 | at handle_var_declaration (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:319:3)
01:50:50.973 | at VariableDeclaration (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:1526:3)
01:50:50.973 | at handle (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:62:2)
01:50:50.973 | at handle_body (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:274:3)
01:50:50.973 | at BlockStatement\|ClassBody (file:///opt/buildhome/repo/node_modules/.pnpm/esrap@1.3.2/node_modules/esrap/src/handlers.js:620:3)
01:50:51.028 | ELIFECYCLE  Command failed with exit code 1.
01:50:51.054 | Failed: Error while executing user command. Exited with error code: 1
01:50:51.063 | Failed: build command exited with code: 1
01:50:51.869 | Failed: error occurred while running build command
</pre>

**Comment by manuel3108** [comment]
Please update to the latest version of `svelte`. This should be fixed as part of [`5.14.3`](https://github.com/sveltejs/svelte/pull/14740)

**Comment by EliBates** [comment]
Thanks this worked.
